import { useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import jsPDF from "jspdf";
import { useTheme } from "./ThemeContext";
import { colors } from "./theme/theme";
//import { useTheme } from "./ThemeContext";
//import { colors } from "./theme/theme";

import "react-circular-progressbar/dist/styles.css";
import {

  CircularProgressbar,
  buildStyles,
} from "react-circular-progressbar";

function ResumeAnalyzer() {
  const navigate = useNavigate();

  // Theme
  const mode = "dark";

const currentTheme = {
  bg: "#0f172a",
  card: "#1e293b",
  text: "#ffffff",
  subText: "#94a3b8",
  border: "#334155",
};
  // States
  const [file, setFile] = useState(null);
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);

  // ===========================
  // Resume Analyze
  // ===========================

  const analyze = async () => {
    if (!file) {
      alert("Please upload a PDF resume.");
      return;
    }

    const formData = new FormData();
    formData.append("file", file);

    try {
      setLoading(true);

      const response = await axios.post(
        "https://ai-career-companion-rxak.onrender.com/upload_resume",
        formData
      );

      setResult(response.data.analysis);

      localStorage.setItem(
        "resumeScore",
        response.data.analysis.resume_score
      );

    } catch (error) {
      console.log(error);

      if (error.response) {
        alert(error.response.data.detail);
      } else {
        alert("Server not running");
      }

    } finally {
      setLoading(false);
    }
  };

  // ===========================
  // Download PDF
  // ===========================

  const downloadPDF = () => {
    if (!result) return;

    const pdf = new jsPDF("p", "mm", "a4");

    pdf.setFillColor(37, 99, 235);
    pdf.rect(0, 0, 210, 30, "F");

    pdf.setTextColor(255, 255, 255);
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(22);
    pdf.text("AI Career Companion", 20, 16);

    pdf.setFontSize(12);
    pdf.text("Professional Resume Analysis Report", 20, 24);

    pdf.setTextColor(0, 0, 0);
    pdf.setFontSize(11);

    pdf.text(
      `Generated : ${new Date().toLocaleString()}`,
      20,
      40
    );

    pdf.setFontSize(18);
    pdf.setFont("helvetica", "bold");
    pdf.text("Resume Score", 20, 55);

    pdf.setFillColor(34, 197, 94);
    pdf.roundedRect(20, 60, 40, 14, 3, 3, "F");

    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(16);
    pdf.text(`${result.resume_score}%`, 30, 70);

    let y = 90;

    pdf.setTextColor(0, 0, 0);
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(16);
    pdf.text("Skills Found", 20, y);

    y += 10;

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(12);

    if (result.skills_found.length === 0) {
      pdf.text("- No skills detected", 25, y);
      y += 8;
    } else {
      result.skills_found.forEach((skill) => {
        pdf.text(`• ${skill}`, 25, y);
        y += 8;
      });
    }

    y += 8;

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(16);
    pdf.text("Recommended Skills", 20, y);

    y += 10;

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(12);

    if (result.missing_skills.length === 0) {
      pdf.text("- No recommendations", 25, y);
      y += 8;
    } else {
      result.missing_skills.forEach((skill) => {
        pdf.text(`• ${skill}`, 25, y);
        y += 8;
      });
    }

    y += 10;

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(16);
    pdf.text("AI Suggestion", 20, y);

    y += 10;

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(12);

    const lines = pdf.splitTextToSize(result.suggestion, 170);

    pdf.text(lines, 20, y);

    y += lines.length * 7 + 20;

    pdf.line(20, y, 190, y);

    y += 10;

    pdf.setFontSize(10);

    pdf.text(
      "Generated by AI Career Companion | Developed by Sneha Sharma",
      20,
      y
    );

    pdf.save("Resume_Report.pdf");
  };
  return (
  <div
    style={{
      minHeight: "100vh",
      background: currentTheme.bg,
      color: currentTheme.text,
      padding: "40px",
      transition: "0.3s",
    }}
  >

    <h1
      style={{
        textAlign: "center",
        fontSize: "42px",
        marginBottom: "10px",
      }}
    >
      📄 AI Resume Analyzer
    </h1>

    <p
      style={{
        textAlign: "center",
        color: currentTheme.subText,
        fontSize: "18px",
        marginBottom: "40px",
      }}
    >
      Upload your resume and receive AI-powered ATS analysis,
      detected skills, improvement suggestions and a professional report.
    </p>

    <div
      style={{
        maxWidth: "900px",
        margin: "0 auto",
        background: currentTheme.card,
        padding: "35px",
        borderRadius: "22px",
        border: `1px solid ${currentTheme.border}`,
        boxShadow:
          mode === "dark"
            ? "0 10px 35px rgba(0,0,0,.35)"
            : "0 10px 35px rgba(0,0,0,.08)",
      }}
    >

      <input
        type="file"
        accept=".pdf"
        onChange={(e) => setFile(e.target.files[0])}
        style={{
          width: "100%",
          padding: "16px",
          borderRadius: "12px",
          border: `1px solid ${currentTheme.border}`,
          background: currentTheme.bg,
          color: currentTheme.text,
          fontSize: "16px",
          marginBottom: "20px",
        }}
      />

      <button
        onClick={analyze}
        disabled={loading}
        style={{
          width: "100%",
          padding: "15px",
          background: "#2563eb",
          color: "white",
          border: "none",
          borderRadius: "12px",
          fontSize: "17px",
          fontWeight: "600",
          cursor: "pointer",
        }}
      >
        {loading ? "Analyzing Resume..." : "🚀 Analyze Resume"}
      </button>

      <button
        onClick={() => navigate("/dashboard")}
        style={{
          width: "100%",
          marginTop: "15px",
          padding: "15px",
          background: "#6b7280",
          color: "white",
          border: "none",
          borderRadius: "12px",
          fontSize: "16px",
          cursor: "pointer",
        }}
      >
        ⬅ Back to Dashboard
      </button>

    </div>
    {result && (
  <div
    style={{
      maxWidth: "900px",
      margin: "40px auto",
      background: currentTheme.card,
      padding: "35px",
      borderRadius: "22px",
      border: `1px solid ${currentTheme.border}`,
      boxShadow:
        mode === "dark"
          ? "0 10px 35px rgba(0,0,0,.35)"
          : "0 10px 35px rgba(0,0,0,.08)",
    }}
  >

    <div
      style={{
        width: "180px",
        height: "180px",
        margin: "0 auto",
      }}
    >
      <CircularProgressbar
        value={result.resume_score}
        text={`${result.resume_score}%`}
        styles={buildStyles({
          pathColor: "#22c55e",
          trailColor:
            mode === "dark"
              ? "rgba(255,255,255,.15)"
              : "#e5e7eb",
          textColor: currentTheme.text,
          textSize: "16px",
        })}
      />
    </div>

    <h2
      style={{
        textAlign: "center",
        marginTop: "20px",
      }}
    >
      Resume Score
    </h2>

    <p
      style={{
        textAlign: "center",
        fontSize: "20px",
        fontWeight: "bold",
        color:
          result.resume_score >= 80
            ? "#22c55e"
            : result.resume_score >= 60
            ? "#f59e0b"
            : "#ef4444",
      }}
    >
      {result.resume_score >= 80
        ? "🌟 Excellent Resume"
        : result.resume_score >= 60
        ? "👍 Good Resume"
        : "⚠ Needs Improvement"}
    </p>

    <hr
      style={{
        margin: "35px 0",
        borderColor: currentTheme.border,
      }}
    />

    <h2>✅ Skills Found</h2>

    <div
      style={{
        display: "flex",
        flexWrap: "wrap",
        gap: "12px",
        marginTop: "20px",
      }}
    >
      {result.skills_found.length === 0 ? (
        <p style={{ color: currentTheme.subText }}>
          No skills detected.
        </p>
      ) : (
        result.skills_found.map((skill, index) => (
          <span
            key={index}
            style={{
              background: "#22c55e",
              color: "white",
              padding: "10px 18px",
              borderRadius: "25px",
              fontWeight: "600",
            }}
          >
            ✔ {skill}
          </span>
        ))
      )}
    </div>

    <hr
      style={{
        margin: "35px 0",
        borderColor: currentTheme.border,
      }}
    />

    <h2>📈 Suggested Skills</h2>

    <div
      style={{
        display: "flex",
        flexWrap: "wrap",
        gap: "12px",
        marginTop: "20px",
      }}
    >
      {result.missing_skills.length === 0 ? (
        <p style={{ color: "#22c55e" }}>
          No additional skills recommended.
        </p>
      ) : (
        result.missing_skills.map((skill, index) => (
          <span
            key={index}
            style={{
              background: "#ef4444",
              color: "white",
              padding: "10px 18px",
              borderRadius: "25px",
            }}
          >
            + {skill}
          </span>
        ))
      )}
    </div>

    <hr
      style={{
        margin: "35px 0",
        borderColor: currentTheme.border,
      }}
    />

    <div
      style={{
        background: currentTheme.bg,
        border: `1px solid ${currentTheme.border}`,
        padding: "25px",
        borderRadius: "16px",
      }}
    >
      <h2 style={{ color: "#2563eb" }}>
        💡 AI Career Suggestion
      </h2>

      <p
        style={{
          color: currentTheme.text,
          lineHeight: "1.8",
        }}
      >
        {result.suggestion}
      </p>
    </div>

    <button
      onClick={downloadPDF}
      style={{
        width: "100%",
        marginTop: "30px",
        padding: "16px",
        border: "none",
        borderRadius: "12px",
        background:
          "linear-gradient(135deg,#2563eb,#7c3aed)",
        color: "white",
        fontSize: "17px",
        fontWeight: "600",
        cursor: "pointer",
      }}
    >
      📄 Download Professional Report
    </button>

  </div>
)}
</div>
);
}

export default ResumeAnalyzer;