import { useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import jsPDF from "jspdf";

import "react-circular-progressbar/dist/styles.css";
import {
  CircularProgressbar,
  buildStyles,
} from "react-circular-progressbar";

function ResumeAnalyzer() {
  const navigate = useNavigate();

  const [file, setFile] = useState(null);
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);

  const analyze = async () => {
    if (!file) {
      alert("Please upload a PDF resume.");
      return;
    }

    const formData = new FormData();
    formData.append("file", file);

    try {
      setLoading(true);

      const response = await axios.post(
        "http://127.0.0.1:8000/upload_resume",
        formData
      );

      setResult(response.data.analysis);
    } catch (error) {
      console.log(error);

      if (error.response) {
        alert(error.response.data.detail);
      } else {
        alert("Server not running");
      }
    } finally {
      setLoading(false);
    }
  };

  const downloadPDF = () => {
    if (!result) return;

    const pdf = new jsPDF("p", "mm", "a4");

    pdf.setFillColor(37, 99, 235);
    pdf.rect(0, 0, 210, 30, "F");

    pdf.setTextColor(255, 255, 255);
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(22);
    pdf.text("AI Career Companion", 20, 16);

    pdf.setFontSize(12);
    pdf.text("Professional Resume Analysis Report", 20, 24);

    pdf.setTextColor(0, 0, 0);
    pdf.setFontSize(11);

    pdf.text(
      `Generated : ${new Date().toLocaleString()}`,
      20,
      40
    );

    pdf.setFontSize(18);
    pdf.setFont("helvetica", "bold");
    pdf.text("Resume Score", 20, 55);

    pdf.setFillColor(34, 197, 94);
    pdf.roundedRect(20, 60, 40, 14, 3, 3, "F");

    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(16);
    pdf.text(`${result.resume_score}%`, 30, 70);

    let y = 90;

    pdf.setTextColor(0, 0, 0);
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(16);
    pdf.text("Skills Found", 20, y);

    y += 10;

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(12);

    if (result.skills_found.length === 0) {
      pdf.text("- No skills detected", 25, y);
      y += 8;
    } else {
      result.skills_found.forEach((skill) => {
        pdf.text(`• ${skill}`, 25, y);
        y += 8;
      });
    }

    y += 8;

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(16);
    pdf.text("Recommended Skills", 20, y);

    y += 10;

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(12);

    if (result.missing_skills.length === 0) {
      pdf.text("- No recommendations", 25, y);
      y += 8;
    } else {
      result.missing_skills.forEach((skill) => {
        pdf.text(`• ${skill}`, 25, y);
        y += 8;
      });
    }

    y += 10;

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(16);
    pdf.text("AI Suggestion", 20, y);

    y += 10;

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(12);

    const lines = pdf.splitTextToSize(result.suggestion, 170);

    pdf.text(lines, 20, y);

    y += lines.length * 7 + 20;

    pdf.line(20, y, 190, y);

    y += 10;

    pdf.setFontSize(10);

    pdf.text(
      "Generated by AI Career Companion | Developed by Sneha Sharma",
      20,
      y
    );

    pdf.save("Resume_Report.pdf");
  };

  return (
    <div
  style={{
    minHeight: "100vh",
    background: "#111827",
    padding: "40px",
    color: "white",
  }}
>
  <h1
    style={{
      textAlign: "center",
      fontSize: "42px",
      marginBottom: "10px",
    }}
  >
    📄 AI Resume Analyzer
  </h1>

  <p
    style={{
      textAlign: "center",
      color: "#cbd5e1",
      fontSize: "18px",
      marginBottom: "40px",
    }}
  >
    Upload your resume and receive an AI-powered analysis with
    resume score, detected skills, missing skills and personalized
    career suggestions.
  </p>

  <div
    style={{
      maxWidth: "900px",
      margin: "0 auto",
      background: "#1f2937",
      padding: "30px",
      borderRadius: "20px",
      border: "1px solid #374151",
      boxShadow: "0 10px 30px rgba(0,0,0,.35)",
    }}
  >
    <input
      type="file"
      accept=".pdf"
      onChange={(e) => setFile(e.target.files[0])}
      style={{
        width: "100%",
        padding: "15px",
        borderRadius: "10px",
        border: "1px solid #374151",
        background: "#111827",
        color: "white",
        fontSize: "16px",
        marginBottom: "20px",
      }}
    />

    <button
      onClick={analyze}
      disabled={loading}
      style={{
        width: "100%",
        padding: "15px",
        background: "#2563eb",
        color: "white",
        border: "none",
        borderRadius: "10px",
        fontSize: "17px",
        fontWeight: "600",
        cursor: "pointer",
      }}
    >
      {loading ? "Analyzing..." : "🚀 Analyze Resume"}
    </button>

    <button
      onClick={() => navigate("/dashboard")}
      style={{
        width: "100%",
        marginTop: "15px",
        padding: "15px",
        background: "#374151",
        color: "white",
        border: "none",
        borderRadius: "10px",
        fontSize: "16px",
        cursor: "pointer",
      }}
    >
      ⬅ Back to Dashboard
    </button>
  </div>

  {result && (
    <div
      style={{
        maxWidth: "900px",
        margin: "40px auto",
        background: "#1f2937",
        padding: "35px",
        borderRadius: "20px",
        border: "1px solid #374151",
        boxShadow: "0 10px 30px rgba(0,0,0,.35)",
      }}
    >
      <div
        style={{
          width: "180px",
          height: "180px",
          margin: "0 auto",
        }}
      >
        <CircularProgressbar
          value={result.resume_score}
          text={`${result.resume_score}%`}
          styles={buildStyles({
            pathColor: "#22c55e",
            trailColor: "rgba(255,255,255,.15)",
            textColor: "#ffffff",
            textSize: "16px",
          })}
        />
      </div>

      <h2
        style={{
          textAlign: "center",
          marginTop: "20px",
          marginBottom: "10px",
        }}
      >
        Resume Score
      </h2>

      <p
        style={{
          textAlign: "center",
          fontSize: "20px",
          fontWeight: "bold",
          color:
            result.resume_score >= 80
              ? "#22c55e"
              : result.resume_score >= 60
              ? "#facc15"
              : "#ef4444",
        }}
      >
        {result.resume_score >= 80
          ? "🌟 Excellent Resume"
          : result.resume_score >= 60
          ? "👍 Good Resume"
          : "⚠ Needs Improvement"}
      </p>

      <hr style={{ margin: "30px 0", borderColor: "#374151" }} />

      <h3 style={{ color: "#22c55e" }}>✅ Skills Found</h3>

      <div
        style={{
          display: "flex",
          flexWrap: "wrap",
          gap: "12px",
          marginTop: "20px",
          marginBottom: "25px",
        }}
      >
                {result.skills_found.length === 0 ? (
          <p>No matching skills found.</p>
        ) : (
          result.skills_found.map((skill, index) => (
            <span
              key={index}
              style={{
                background: "#22c55e",
                color: "white",
                padding: "10px 18px",
                borderRadius: "25px",
                fontWeight: "600",
              }}
            >
              ✔ {skill}
            </span>
          ))
        )}
      </div>

      <hr
        style={{
          margin: "30px 0",
          borderColor: "#374151",
        }}
      />

      <h3
        style={{
          color: "#ef4444",
          marginBottom: "20px",
        }}
      >
        📈 Suggested Skills
      </h3>

      <div
        style={{
          display: "flex",
          flexWrap: "wrap",
          gap: "12px",
          marginBottom: "30px",
        }}
      >
        {result.missing_skills.length === 0 ? (
          <p style={{ color: "#22c55e" }}>
            No suggested skills.
          </p>
        ) : (
          result.missing_skills.map((skill, index) => (
            <span
              key={index}
              style={{
                background: "#ef4444",
                color: "white",
                padding: "10px 18px",
                borderRadius: "25px",
                fontWeight: "600",
              }}
            >
              + {skill}
            </span>
          ))
        )}
      </div>

      <hr
        style={{
          margin: "30px 0",
          borderColor: "#374151",
        }}
      />

      <div
        style={{
          background: "#111827",
          border: "1px solid #374151",
          padding: "25px",
          borderRadius: "16px",
        }}
      >
        <h3
          style={{
            color: "#60a5fa",
            marginBottom: "15px",
          }}
        >
          💡 AI Career Suggestion
        </h3>

        <p
          style={{
            color: "#e5e7eb",
            lineHeight: "1.8",
            fontSize: "16px",
          }}
        >
          {result.suggestion}
        </p>
      </div>

      <button
        onClick={downloadPDF}
        style={{
          width: "100%",
          marginTop: "30px",
          padding: "16px",
          border: "none",
          borderRadius: "12px",
          background: "linear-gradient(135deg,#2563eb,#7c3aed)",
          color: "white",
          fontSize: "17px",
          fontWeight: "600",
          cursor: "pointer",
        }}
      >
        📄 Download Professional Report
      </button>
    </div>
  )}

</div>
);
}

export default ResumeAnalyzer;